#!/bin/bash

#IP=`ip addr show eth0 | grep 'inet ' | cut -d/ -f1 | awk '{print $2}'`
#sed -i "s/@IP@/$IP/g" /opt/hbase/conf/hbase-site.xml

echo "STARTING HBASE..."
(

$HBASE_HOME/bin/hbase master start

) & (

sleep 5

echo "STARTING HIVE..."
$HIVE_HOME/bin/hiveserver2

)